version: "3.7"
services:
  awsddns:
    container_name: awsddns
    image: "errorbe/awsddns"
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LOCAL_USER_ID=1000
      - LOCAL_GROUP_ID=1000
    volumes:
      - /home/koen/awsddns:/home/spring/config:Z
      - /home/koen/awsddns/logs:/home/spring/logs:Z
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
